[package]
name = "unreal"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.15.0-rc.3"
bevy_hierarchy = "0.15.0-rc.3"
bevy_math = "0.15.0-rc.3"
bevy_utils = "0.15.0-rc.3"
log = { version = "0.4.22", features = ["std"] }

[build-dependencies]
bindgen = "0.70.1"